publishdir = "./docs"
baseurl = "https://git.andrewandlaura.com/"
languageCode = "en-gb"
title = "Andrew and Laura"
SectionPagesMenu = "main"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -110
